#!/usr/bin/env python3
"""Run live MCP tool discovery and format output for docs/mcp-tools-discovered.md.

Developer utility script to refresh ground truth tool definitions.
Usage:
    python3 scripts/discover_mcp_tools.py
"""

import json
import sys
from pathlib import Path

# Add project root to sys.path
root_dir = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root_dir))

from agent.mcp.client import DataHubMCPClient


def main():
    print("Connecting to DataHub MCP Server via stdio...")
    with DataHubMCPClient() as client:
        tools = client.list_tools()

    print(f"\nDiscovered {len(tools)} tools:")
    for t in tools:
        print(f"  - {t['name']}")

    doc_path = root_dir / "docs" / "mcp-tools-discovered.md"

    md_content = []
    md_content.append("# Ground Truth DataHub MCP Tools Discovered\n")
    md_content.append("Generated by live `tools/list` RPC round-trip against local DataHub GMS v1.7.0.\n")
    md_content.append("## Authentication & Environment Reference")
    md_content.append("- **DataHub GMS URL**: `http://localhost:8080`")
    md_content.append("- **PAT Name**: `lineage-marshal-hackathon`")
    md_content.append("- **PAT Expiry Date**: 2026-11-06 (89 days validity)")
    md_content.append("- **Setup Architecture**: Self-hosted DataHub OSS via `mcp-server-datahub` (stdio subprocess transport).")
    md_content.append("- **Mutation Mode**: Enabled (`TOOLS_IS_MUTATION_ENABLED=true`)\n")
    md_content.append("## Discovered Tools Summary\n")
    md_content.append(f"Total tools discovered: **{len(tools)}**\n")
    md_content.append("| Tool Name | Description | Key Arguments |")
    md_content.append("| --- | --- | --- |")

    for t in tools:
        name = t.get("name", "")
        desc = t.get("description", "").replace("\n", " ")
        schema = t.get("inputSchema", {})
        props = schema.get("properties", {})
        args_str = ", ".join(props.keys()) if props else "None"
        md_content.append(f"| `{name}` | {desc[:120]}... | `{args_str}` |")

    md_content.append("\n## Detailed Tool Schemas (JSON Ground Truth)\n")
    md_content.append("```json")
    md_content.append(json.dumps(tools, indent=2))
    md_content.append("```\n")

    doc_path.write_text("\n".join(md_content))
    print(f"\nSaved discovery doc to {doc_path}")


if __name__ == "__main__":
    main()
